- README.md
- builders.json
- package.json
- src/builders/browser/index.ts
- src/builders/browser/schema.d.ts
- src/builders/browser/schema.json
- tsconfig.json
- yarn.lock
Testing:
**Angular CLI doesn't properly resolve `npm link` packages, follow these steps to test:**
* build package
* run `npm pack` 
* copy `single-spa-angular-2.1.0.tgz` to an Angular CLI project
* run `npm install single-spa-angular-2.1.0.tgz`
* follow directions in `README`
🎊 
Related to #14
> feat(builder): Angular CLI builder for bundling single module

- README.md
- src/builders/browser/index.ts
> feat(builder): use project name if libraryName is not configured

- .babelrc
- README.md
- builders.json
- jest.config.js
- package-lock.json
- package.json
- schematics.json
- src/builders/browser/index.ts
- src/schematics/library-versions.ts
- src/schematics/ng-add/_files/src/main.single-spa.ts.template
- src/schematics/ng-add/index.spec.ts
- src/schematics/ng-add/index.ts
- src/schematics/ng-add/schema.d.ts
- src/schematics/ng-add/schema.json
- src/schematics/utils.ts
- tsconfig.json
> feat(schematics): add ng-add schematic

- src/builders/single-spa-webpack-builder.ts
- src/schematics/ng-add/schema.json
> Using defaultProjectName() as webpack libraryName. Resolves #45

- src/schematics/ng-add/index.spec.ts
- src/schematics/ng-add/index.ts
Hi,
This was the other issue mentioned in #66 .
I guess to be certain that it's working as intended, more tests could be implemented, one with defaultProject and one where specifying project.
> ng add with project option

- src/browser-lib/single-spa-angular.ts
Should fix https://github.com/CanopyTax/single-spa-angular/issues/53
> Read/write the same type to zone properties.

- package-lock.json
- src/builders/single-spa-webpack-builder.ts
- src/webpack/index.ts
See related https://github.com/systemjs/systemjs#compatibility-with-webpack
> Better interop with systemjs

- src/schematics/ng-add/index.spec.ts
- src/schematics/ng-add/index.ts
> fix: consider project root when registerting path to main and Webpack config

- src/browser-lib/patch-router.ts
- src/browser-lib/single-spa-angular.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: N/A
```
[ ] Yes
[ ] No
```
> fix: patch router and wrap `scheduleNavigation` calls into `zone.run`

- src/browser-lib/patch-router.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: 179
If the angular version is less than 6, the `router.scheduleNavigation` is made with a slightly different set of params.
```
[ ] Yes
[x] No
```
> fix(single-spa-angular): separate router patch for Angular 6+ and older

- cypress/integration/issue-113.js
- integration/chat/src/app/pages/groups/groups.component.html
- integration/chat/src/app/pages/groups/groups.component.ts
- integration/portal/package.json
- integration/portal/yarn.lock
- package.json
- src/src/extra-providers.ts
- src/src/single-spa-angular.ts
- yarn.lock
> fix: resolve infinite redirects by ignoring non-browser PopStateEvents and cleanup resources when app gets destroyed

- .npmignore
- package-lock.json
- package.json
- rollup.config.js
- src/schematics/ng-add/index.ts
- tsconfig.spa.json
> build: target ES5 and ES2015 for `single-spa-angular@3.x` to support differential loading

- .gitignore
- integration/portal/package.json
- integration/portal/yarn.lock
- schematics/ng-add/index.ts
- schematics/ng-add/tests/index.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #249 
The schematic doesn't manage to parse the tsconfig with comments.
Comments in tsconfig are ignored.
```
[ ] Yes
[x] No
```
> fix: support the Angular 10 comments in the tsconfig file (fixes #249)

- src/src/single-spa-angular.ts
- src/src/types.ts
- [ x] Tests for the changes have been added (for bug fixes / features)
```
[x ] Bugfix
[ ] Feature
```
bootstrapFunction(props: AppProps): Promise<NgModuleRef<any>>;
Issue Number: https://github.com/single-spa/single-spa-angular/issues/281
bootstrapFunction(props: AppProps & T): Promise<NgModuleRef<any>>;
```
[ ] Yes
[x ] No
```
> fix: add custom props generic for bootstrapFunction

- schematics/ng-add/index.ts
> fix: use `JSON.stringify` except of `JSON5.stringify`

- libs/single-spa-angular/webpack/index.ts
- [ X ] Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[ X ] Feature
```
In the webpack config, the libraryName is take from the angular config from files: angular.json and .angular.json.
Be able to load angular config from workspace.json (from Nrwl/Nx framework)
```
[ ] Yes
[ X ] No
```
> feat: make it compatible with angular config in workspace.json file

- schematics/ng-add/dependencies.ts
- schematics/ng-add/index.ts
> fix: install the `latest` custom Webpack package version

- schematics/ng-add/index.ts
> fix: normalize paths before overwriting configuration

- apps/parcel/src/app/ReactWidget/ReactWidget.tsx
- apps/parcel/src/app/app.component.html
- apps/parcel/src/app/app.component.ts
- cypress/integration/parcel.spec.js
See #338. This PR confirms that custom props are passed successfully to parcels.
> test: props passed to parcels. see #338

- schematics/ng-add/index.ts
- schematics/ng-add/tests/issue-341.spec.ts
> feat: show warning during `ng-add` schematic if routing is enabled

- libs/single-spa-angular/webpack/index.spec.ts
- libs/single-spa-angular/webpack/index.ts
- [x ] Tests for the changes have been added (for bug fixes / features)
```
[ x] Bugfix
[ ] Feature
```
Issue Number: 366
```
[ ] Yes
[x ] No
```
> fix: compilation failed due to wrong webpack configuration (#366)

- libs/single-spa-angular/package.json
- libs/single-spa-angular/webpack/__snapshots__/index.spec.ts.snap
- libs/single-spa-angular/webpack/index.ts
- package.json
```
[ ] Bugfix
[ ] Feature
[X] Build related changes
```
The Webpack rule `"parser": {"system": false }` has been removed from Webpack 5. This causes an error in compile time due to  @angular-builders/custom-webpack v12 using Webpack 5.
Issue Number: #379 
The Angular 12 microfrontend is correctly compiled.
```
[ ] Yes
[X] No
```
At least I don't think it does but maybe I'm wrong here.
All of Jest and Cypress tests passed on local.
> fix: invalid parser object (issue #379)

- jest.config.js
- libs/single-spa-angular/package.json
- package.json
- schematics/migration.json
- schematics/ng-add/tests/utils.ts
- schematics/ng-update/index.ts
- schematics/ng-update/tests/v5.spec.ts
- tsconfig.base.json
- tsconfig.schematics.json
- yarn.lock
Users need to fix a breaking change when upgrading to `single-spa-angular@^5` manually.
Issue Number: #455
Running `ng update single-spa-angular@5` removes `AnimationEngine` and automatically fixes https://github.com/single-spa/single-spa-angular/pull/362#discussion_r640970908.
> feat: create v5 update schematic
