single-spa/single-spa-angular

README.md
src/single-spa-angular2.js

See #1, https://github.com/CanopyTax/single-spa/issues/115, https://github.com/angular/angular/issues/19079, and http://plnkr.co/edit/43a4sWEsdm5yfpVkJ5Zs?p=preview

Fix #1. Workaround for angular not cleaning up routing events when module is destroyed.

---

src/single-spa-angular2.js

It would be great if we could pass the instantiated module down to the middle ware. This is especially useful since this (https://github.com/CanopyTax/single-spa/pull/156) PR has been merged. Here is a simple use case for this:
```js
// root-application.js
singleSpa.registerApplication('app1', () =>  {}, () => {}, {authToken: "d83jD63UdZ6RS6f70D0"});
```
```js
// app.js
export function mount(props) {
return ngLifecycles.mount(props).then((module) => {
module.instance.setAuthToken(props.customProps.authToken);
});
}
```
```js
// main-module.ts
@NgModule({
// ...
})
export default class MainModule {
setAuthToken(authToken) {
// do something with the authToken
}
}
```
Our actual use case is to pass down a reference to the communication layer which we use for inter-app-communication. So there …

The lifecycle method 'mount' does receive the module instance now

---

.babelrc
README.md
package.json
src/single-spa-angular.js
yarn.lock

There was some change with Angular 7 that caused us to need to do an applicationRef.tick() whenever a popstate or hashchange event goes through single-spa. See the comment in the code in this PR for more details.

Support for angular 7, including angular@router 7.

---

README.md
src/schematics/ng-add/_files/src/main.single-spa.ts.template
src/single-spa-angular.ts

`bootstrapFunction` is a new required opt to singleSpaAngular's runtime library. `mainModule` and `platform` are no more.
This takes the bundle size of a hello world app from 500kb to 260kb when you do `ng build --prod`

New bootstrapFunction, which tree shaking dead code. Resolves #31.

---

package-lock.json
src/builders/single-spa-webpack-builder.ts

If defaultProject is set in angular.json it will take precedence over the --project option.
Mentioned this in #66 .

Fixing --project option in builder

---

src/browser-lib/single-spa-angular.ts

Hi, this change makes possible to use the customProps from the register application into the singleSpaAngular bootstrapFunction. for example: 
```javascript
bootstrapFunction: (props) => platformBrowserDynamic(
{provide: 'environment', useValue: props.environment }
]).bootstrapModule(AppModule)
```

Added props to bootstrapFunction

---

src/browser-lib/single-spa-angular.ts

Following our discussion in #140.
I just added an optional opts updateFunction that is directly set as the update lifecycle of the produced parcel/app. The user can use it to update its local singleSpaProps subject.

Add optional update lifecycle to singleSpaAngular

---

src/schematics/ng-add/_files/extra-webpack.config.js.template
src/schematics/ng-add/_files/src/app/empty-route/empty-route.component.ts.template
src/schematics/ng-add/_files/src/main.single-spa.ts.template
src/schematics/ng-add/_files/src/single-spa/asset-url.ts.template
src/schematics/ng-add/_files/src/single-spa/single-spa-props.ts.template

fix: resolve lint issues

---

package-lock.json
package.json
src/browser-lib/single-spa-angular.ts
src/schematics/ng-add/index.spec.ts
src/schematics/ng-add/index.ts
src/webpack/index.ts

Hey @joeldenning
This PR provides fixes for 3 issues:
* it updates `tsconfig.app.json.files` to contain path to `main.single-spa.ts`
* it excludes `polyfills-es5` from Webpack entries to fix Terser error
* destroys bootstrapped module after calling `flush()` and removes DOM nodes if Ivy is enabled
I have updated Angular to 9 version in the current project, it required to update `runSchematic` to `runSchematicAsync` since it's deprecated, that's what I did in the `index.spec.ts` file.
Actually I wanted to kill 2 birds with one stone :D
But there is a problem with builders (browser and dev-server in `src/builders`). It cannot be built since most of the functionality is not exported anymore `@angular-devkit/build-angular` (it contained breaking changes in Angular 8).
IMHO those builders have …

fix: add `main.single-spa.ts` to compilation and exclude `polyfills-es5` from Webpack entries

---

package-lock.json
package.json
src/schematics/ng-add/index.ts

Joel, this check for Angular has to be removed in the future IMO, because Angular 7 LTS ends on 18 April 2020. We'd want to maintain only stable versions.

refactor: remove `semver` from dependencies

---

schematics/ng-add/index.ts
schematics/ng-add/tests/add-scripts.spec.ts
schematics/ng-add/tests/index.spec.ts
schematics/ng-add/tests/issue-168.spec.ts

fix(schematics): disable output hashing in configurations

---

cypress/integration/issue-113.js
integration/chat/package.json
integration/chat/src/app/app-routing.module.ts
integration/chat/src/app/app.component.html
integration/chat/src/app/app.module.ts
integration/chat/src/app/components/chat/chat.component.html
integration/chat/src/app/pages/groups/groups-routing.module.ts
integration/chat/src/app/pages/groups/groups.component.html
integration/chat/src/app/pages/groups/groups.component.ts
integration/chat/src/app/pages/groups/groups.module.ts
integration/chat/src/app/pages/rooms/rooms-routing.module.ts
integration/chat/src/app/pages/rooms/rooms.component.html
integration/chat/src/app/pages/rooms/rooms.component.ts
integration/chat/src/app/pages/rooms/rooms.module.ts
integration/chat/yarn.lock

Just added a simple test that reproduces an issue with infinite redirects.

test: add end-to-end test that reproduces #113 issue

---

.eslintrc
src/internals/package.json
src/internals/src/dom.ts
src/internals/src/index.ts
src/internals/src/types.ts
src/package.json
src/src/single-spa-angular.ts
tsconfig.json

Internal functions are moved into a separate package. This will be possible to re-use them when implementing additional packages for `@angular/elements` and `renderComponent`.

build(single-spa-angular): move internal functions to `single-spa-angular/internals` package

---

schematics/ng-add/dependencies.ts
schematics/ng-add/index.ts
schematics/ng-add/tests/index.spec.ts

```
[ ] Bugfix
[x] Feature
```
Single-spa is a peerDependency so it is not installed when the schematic is being run, which means that users have to manually install it after a project is created with create-single-spa. Its annoying at best, frustrating at worst because users don't understand why it doesn't work right after creating.
Issue Number: https://github.com/single-spa/create-single-spa/issues/106 
this issue is logged with create-single-spa but I believe it'd be better to implement here in …

feat: install single-spa dependency in angular schematic

---

.eslintrc
.github/workflows/single-spa-angular.yml
src/browser-lib/single-spa-angular.ts
src/builders/single-spa-webpack-builder.ts
src/webpack/index.ts

Since we support 3.x because there are a lot of apps that still run using Angular 6-8 I would love to have this as a quality gateway.

ci: setup actions for `3.x`

---

package.json

Include ignored builders.json and schematics.json files into package so ng add
will stop complain about missing collections.
Closes: #226

fix: revive schematics functionality

---

schematics/ng-add/_files/extra-webpack.config.js.template
schematics/ng-add/index.ts
schematics/ng-add/tests/index.spec.ts
src/webpack/index.ts

Sorry for the delay in getting this put together.
This pull request incorporates two different approaches. The two different commits show each of the approaches.
The first approach is simply a string parameter passed to `singleSpaAngularWebpack`. To be backwards compatible, it falls back to trying to get the project name from angular.json. If that fails, it uses a default value, and prints a warning message that explains why a default value might be undesirable, and a link to information on how to fix it.
The second approach is similar, but uses a property defined in angular.json. It has equivalent fallback to the first approach. For this second approach, I've also shown an example of another property (`libraryTarget`) that might be helpful, especially since that was supported back …

Library Name

---

package-lock.json
package.json
src/schematics/ng-add/index.ts
src/webpack/index.ts

3.x branch version of library name fix.
I had to add '@angular/cli' as a dev dependency, as otherwise typescript would break trying to type-check the imported findUp method. The file that needs it is only used by angular cli version 8 or newer, so we can be sure the user will have that package installed at runtime. I did however use version 7 in the dev dependency, so as to be consistent with the angular version used with the rest of the package. This is fine since the function is present with the same type signature in that version too. The side effect is that 
I expect CI will fail, due to linting errors. Running `npm run lint` even on the unmodified 3.x branch is causing a bunch of linting errors on my system. I do not think that fixing pre-existing lint errors was in scope for this …

Library name [3.x]

---

src/webpack/index.spec.ts
src/webpack/index.ts

PR concerning my post on [https://single-spa.slack.com/archives/C8R6U7MT7/p1599556983407100](slack)
The MiniCssExtract plugin should be replaced by style-laoder in the webpack config.
Correctly replaced:
```
{ 
module: { 
rules: [ { use: ['mini-css-extract-plugin'] } ]
}
```
Not replaced:
```
{ 
module: { 
rules: [ { use: [{loader:'mini-css-extract-plugin'}] } ]
}
```
Issue Number: N/A
You can now receive loader specified as objects
```
[ ] Yes
[ X ] No
```

fix: allow removal mini-css-extract from object rules

---

src/webpack/index.spec.ts
src/webpack/index.ts

- [x ] Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[x ] Feature
```
Current webpack always removes the MiniCssExtract plugin which is used in Angular projects to generate css files, instead using the style-loader to inject the css as "style" tags. We require the files to be generated so that we can manually control them, because the styles injected are not remove at unmount time.
Issue Number: N/A
Add "extraOptions" parameter …

refactor(webpack): add extraOptions param for default webpack export

---

libs/single-spa-angular/internals/package.json

Closes #204 
This provides a valid UMD id for the `internals` package. Since `single-spa-angular` tries to resolve the `single-spa-angular/internals` package using `single-spa-angular-internals` id, but ng-packagr generated `single-spa-angular/internals` UMD id.

fix: provide `umdId` for the `single-spa-angular/internals`

---

schematics/ng-add/_files/src/main.single-spa.ts.template
schematics/ng-add/index.ts

This PR removes an unused code, since we have a semver requirements inside our package.json `@angular/core: >=9`.

chore: drop old Angular related code

---

schematics/ng-add/index.ts
schematics/ng-add/rules/add-npm-scripts.ts
schematics/ng-add/rules/update-configuration.ts
schematics/ng-add/rules/utils.ts
schematics/ng-add/schema.d.ts
schematics/ng-add/schema.json
schematics/ng-add/tests/add-scripts.spec.ts

Hey @joeldenning . The `--deploy-url` is deprecated:
Updated schematics to provide `deployUrl` through `angular.json`.
Also added `port` option to schema since it will be easier to ask user for the port except of trying to detect it manually.

fix: provide `deployUrl` through build target instead `--deploy-url`

---

libs/single-spa-angular/webpack/index.ts

Included a fix from that comment: https://github.com/single-spa/single-spa-angular/issues/395#issuecomment-994475359

fix: specify `webSocketURL` within the webpack config

---

.github/FUNDING.yml

Open Collective is shutting down - see https://opencollective.com/foundation/updates/announcement-we-are-dissolving-open-collective-foundation-at-the-end-of-this-year
Happy to add other Github sponsor profiles to this project, since I'm not the primary maintainer of this repository.

Remove Open Collective
